# Generated by Django 5.2 on 2026-06-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tikina',
            field=models.CharField(blank=True, choices=[('lakeba', 'Lakeba'), ('nayau', 'Nayau'), ('oneata', 'Oneata'), ('moce', 'Moce'), ('kabara', 'Kabara'), ('fulaga', 'Fulaga'), ('ono_i_lau', 'Ono-i-Lau'), ('lomaloma', 'Lomaloma'), ('mualevu', 'Mualevu'), ('cicia', 'Cicia'), ('moala', 'Moala'), ('matuku', 'Matuku'), ('totoya', 'Totoya')], help_text='Leave blank for province-wide events', max_length=100),
        ),
    ]
