# Generated by Django 5.2 on 2026-07-15

import news.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("news", "0001_initial")]
    operations = [
        migrations.AddField(model_name="newspost", name="news_type", field=models.CharField(choices=[("article", "Article News"), ("photo", "Photo News"), ("video", "Video News")], default="article", max_length=20)),
        migrations.AlterField(model_name="newspost", name="body", field=models.TextField(blank=True, help_text="Full article body. Supports basic HTML.")),
        migrations.AddField(model_name="newspost", name="video_file", field=models.FileField(blank=True, null=True, upload_to="news/videos/%Y/%m/", validators=[news.models.validate_video_upload])),
        migrations.AddField(model_name="newspost", name="video_thumbnail", field=models.ImageField(blank=True, null=True, upload_to="news/video-thumbnails/%Y/%m/", validators=[news.models.validate_gallery_image])),
        migrations.AddField(model_name="newspost", name="video_url", field=models.URLField(blank=True, help_text="Paste a YouTube or supported external video URL.")),
        migrations.CreateModel(name="NewsPhoto", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("image", models.ImageField(upload_to="news/photos/%Y/%m/", validators=[news.models.validate_gallery_image])), ("caption", models.CharField(blank=True, max_length=255)), ("display_order", models.PositiveIntegerField(default=0)), ("created_at", models.DateTimeField(auto_now_add=True)), ("news", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="photos", to="news.newspost"))], options={"ordering": ["display_order", "id"]}),
    ]
