# Generated by Django 5.2 on 2026-06-17 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turagaprofile',
            name='mataqali',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='turagaprofile',
            name='membership_type',
            field=models.CharField(choices=[('turaga_ni_koro', 'Turaga ni Koro'), ('mata_ni_tikina', 'Mata ni Tikina'), ('turaga_ni_yavusa', 'Turaga ni Yavusa'), ('roko', 'Roko / Provincial Staff')], default='turaga_ni_koro', max_length=30),
        ),
        migrations.AddField(
            model_name='turagaprofile',
            name='tokatoka',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='turagaprofile',
            name='vanua',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='turagaprofile',
            name='yavusa',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
