# Generated by Django 5.2 on 2026-06-24 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_turagaprofile_mataqali_turagaprofile_membership_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('turaga_ni_koro', 'Turaga ni Koro'), ('mata_ni_tikina', 'Mata ni Tikina'), ('liuliu_ni_yavusa', 'Liuliu ni Yavusa'), ('roko_admin', 'Roko Admin')], max_length=50)),
                ('tikina', models.CharField(blank=True, max_length=100)),
                ('koro', models.CharField(blank=True, max_length=100)),
                ('yavusa', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
