# Generated by Django 5.2 on 2026-06-25 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text="FontAwesome icon class, e.g. 'fa-file-pdf'", max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Document Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF Document'), ('docx', 'Word Document'), ('xlsx', 'Excel Spreadsheet'), ('pptx', 'PowerPoint Presentation'), ('image', 'Image'), ('other', 'Other')], default='pdf', max_length=10)),
                ('file_size_kb', models.PositiveIntegerField(default=0, editable=False, help_text='Auto-calculated on save')),
                ('access_level', models.CharField(choices=[('public', 'Public - Anyone can download'), ('login', 'Login Required - Any authenticated user'), ('koro', 'Turaga ni Koro and above'), ('tikina', 'Mata ni Tikina and above'), ('admin', 'Roko Admin only')], default='public', max_length=20)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags, e.g. minutes, 2024, Lakeba', max_length=200)),
                ('year', models.PositiveIntegerField(blank=True, help_text='Document year for filtering', null=True)),
                ('version', models.CharField(blank=True, help_text='e.g. v1.0, Rev 2', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('download_count', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_uploaded', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documentcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
