# Generated by Django 5.2 on 2026-06-30 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mata_ni_tikina', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MNTReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(choices=[('Q1', 'Q1 - January to March'), ('Q2', 'Q2 - April to June'), ('Q3', 'Q3 - July to September'), ('Q4', 'Q4 - October to December')], max_length=2)),
                ('year', models.PositiveIntegerField()),
                ('full_name', models.CharField(max_length=150)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('village', models.CharField(max_length=150)),
                ('tikina', models.CharField(max_length=150)),
                ('province', models.CharField(max_length=150)),
                ('tikina_population', models.PositiveIntegerField(default=0)),
                ('announcements_made_count', models.PositiveIntegerField(default=0)),
                ('traditional_announcements_received_count', models.PositiveIntegerField(default=0)),
                ('villages_surveyed_count', models.PositiveIntegerField(default=0)),
                ('villages_pending_survey_count', models.PositiveIntegerField(default=0)),
                ('council_head_name', models.CharField(max_length=150)),
                ('council_head_age', models.PositiveIntegerField(blank=True, null=True)),
                ('council_turaga_count', models.PositiveIntegerField(default=0)),
                ('council_marama_count', models.PositiveIntegerField(default=0)),
                ('council_daunivakasala_count', models.PositiveIntegerField(default=0)),
                ('council_meeting_frequency', models.CharField(blank=True, max_length=150)),
                ('council_additional_notes', models.TextField(blank=True)),
                ('coordination_additional_notes', models.TextField(blank=True)),
                ('has_development_plan', models.CharField(blank=True, choices=[('io', 'Io'), ('sega', 'Sega')], max_length=10)),
                ('education_council_decision', models.TextField(blank=True)),
                ('income_trend', models.CharField(blank=True, choices=[('tubucake', 'Tubucake'), ('rawa_vakatikina', 'Rawa Vakatikina'), ('lutusobu', 'Lutu Sobu')], max_length=20)),
                ('income_council_decision', models.TextField(blank=True)),
                ('infrastructure_trend', models.CharField(blank=True, choices=[('tubucake', 'Tubucake'), ('rawa_vakatikina', 'Rawa Vakatikina'), ('lutusobu', 'Lutu Sobu')], max_length=20)),
                ('villages_with_phone_count', models.PositiveIntegerField(default=0)),
                ('villages_with_tv_count', models.PositiveIntegerField(default=0)),
                ('boat_count', models.PositiveIntegerField(default=0)),
                ('vehicle_count', models.PositiveIntegerField(default=0)),
                ('villages_with_road_access_count', models.PositiveIntegerField(default=0)),
                ('new_roads_built_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('development_council_decision', models.TextField(blank=True)),
                ('govt_financial_assistance_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('govt_assisting_department', models.CharField(blank=True, max_length=200)),
                ('govt_official_visits_count', models.PositiveIntegerField(default=0)),
                ('govt_projects_covered', models.TextField(blank=True)),
                ('govt_partnership_notes', models.TextField(blank=True)),
                ('ngo_awareness_programs_notes', models.TextField(blank=True)),
                ('ngo_financial_assistance_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ngo_program_name', models.CharField(blank=True, max_length=200)),
                ('ngo_project_equipment_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ngo_project_name', models.CharField(blank=True, max_length=200)),
                ('ngo_partnership_notes', models.TextField(blank=True)),
                ('council_funds_held', models.CharField(blank=True, choices=[('io', 'Io'), ('sega', 'Sega')], max_length=10)),
                ('soli_target_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('soli_contributor_count', models.PositiveIntegerField(default=0)),
                ('soli_collected_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('soli_balance_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('soli_collection_method', models.TextField(blank=True)),
                ('fund_growth_notes', models.TextField(blank=True)),
                ('has_registered_farmland', models.CharField(blank=True, choices=[('io', 'Io'), ('sega', 'Sega')], max_length=10)),
                ('farmland_lease_count', models.PositiveIntegerField(default=0)),
                ('farmland_acres_leased', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('farmland_lease_years_covered', models.CharField(blank=True, max_length=150)),
                ('farmland_development_notes', models.TextField(blank=True)),
                ('reps_attend_meetings', models.CharField(blank=True, choices=[('io', 'Io'), ('sega', 'Sega')], max_length=10)),
                ('reps_understand_training_needs', models.CharField(blank=True, choices=[('io', 'Io'), ('sega', 'Sega')], max_length=10)),
                ('reps_assist_report_writing', models.CharField(blank=True, choices=[('io', 'Io'), ('sega', 'Sega')], max_length=10)),
                ('reps_help_outside_meetings', models.CharField(blank=True, choices=[('io', 'Io'), ('sega', 'Sega')], max_length=10)),
                ('reps_additional_notes', models.TextField(blank=True)),
                ('reps_council_decision', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mnt_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KoroUnderTikina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village_name', models.CharField(max_length=150)),
                ('traditional_leader', models.CharField(blank=True, max_length=150)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='koro_under_tikina', to='mata_ni_tikina.mntreport')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeSourceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('business', 'Business'), ('farming', 'Farming'), ('fishing', 'Fishing'), ('forest_land_use', 'Forest/Land Use'), ('handicrafts', 'Handicrafts')], max_length=50)),
                ('ownership_or_detail', models.CharField(blank=True, max_length=200)),
                ('count_or_amount', models.PositiveIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_sources', to='mata_ni_tikina.mntreport')),
            ],
        ),
        migrations.CreateModel(
            name='FundCollectionChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.CharField(choices=[('road_access', 'Road Access'), ('no_market', 'No Market'), ('no_boat_or_lorry', 'No Boat/Lorry'), ('low_produce_price', 'Low Produce Price'), ('low_value_goods', 'Low Value Goods')], max_length=50)),
                ('selected', models.BooleanField(default=False)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_challenges', to='mata_ni_tikina.mntreport')),
            ],
        ),
        migrations.CreateModel(
            name='CouncilSavingsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(choices=[('anz', 'ANZ'), ('westpac', 'Westpac'), ('colonial', 'Colonial'), ('fijian_holdings', 'Fijian Holdings'), ('unit_trust_fiji', 'Unit Trust of Fiji')], max_length=50)),
                ('saving_level', models.CharField(choices=[('vakavuvale', 'Vakavuvale'), ('vakaitokatoka', 'Vakaitokatoka'), ('vakamataqali', 'Vakamataqali'), ('vakoro', 'Vakoro'), ('vaka_tamata_yadua', 'Vaka Tamata Yadua')], max_length=50)),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_accounts', to='mata_ni_tikina.mntreport')),
            ],
        ),
        migrations.CreateModel(
            name='SettlementRegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('registered', 'Registered')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_registrations', to='mata_ni_tikina.mntreport')),
            ],
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('mata_ni_tikina', 'Mata ni Tikina'), ('liuliu_ni_matabose', 'Liuliu ni Matabose'), ('roko_veivuke', 'Roko Veivuke'), ('roko_tui', 'Roko Tui'), ('dauniyau_ni_yasana', 'Dauniyau ni Yasana')], max_length=50)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('signed', models.BooleanField(default=False)),
                ('signed_date', models.DateField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='mata_ni_tikina.mntreport')),
            ],
        ),
        migrations.CreateModel(
            name='TikinaChallengeIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(choices=[('solesolevaki', 'Solesolevaki'), ('makete', 'Vakavinakataki na Makete'), ('gaunisala', 'Vakavinakataki na Gaunisala'), ('waqa', 'Vakavinakataki na Waqa'), ('vodovodo', 'Veivuke ni Vodovodo'), ('qele_bulabula', 'Veirauti Vinaka/Qele Bulabula'), ('takiveiyaga', 'Takiveiyaga'), ('mamaca', 'Rui Mamaca/Dravuisiga'), ('suasua', 'Rui Levu na Suasua'), ('qele_matemate', 'Qele Matemate')], max_length=50)),
                ('selected', models.BooleanField(default=False)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_indicators', to='mata_ni_tikina.mntreport')),
            ],
        ),
        migrations.CreateModel(
            name='TikinaCoordinationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(choices=[('yavusa_leadership', 'Yavusa Leadership'), ('mataqali_leadership', 'Mataqali Leadership'), ('church_leadership', 'Church Leadership'), ('organization_leadership', 'Organization Leadership')], max_length=50)),
                ('status', models.CharField(blank=True, choices=[('matata', 'Matata/Rokovi'), ('buwawa', 'Buwawa/Luluqa'), ('leqa_levu', 'Leqa Vakalevu')], max_length=20)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordination_statuses', to='mata_ni_tikina.mntreport')),
            ],
        ),
        migrations.CreateModel(
            name='TikinaDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('resolution', models.TextField(blank=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='mata_ni_tikina.mntreport')),
            ],
        ),
        migrations.CreateModel(
            name='TikinaIncomeActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[('tei_dovu_suka', 'Tei Dovu & Suka'), ('koula_volitaki', 'Koula Volitaki'), ('niu_volitaki', 'Niu Volitaki'), ('tolo_kau_maroroi', 'Volitaki ni Tolo ni Kau Maroroi'), ('qoli_volitaki_ika', 'Na Qoli & Volitaki Ika'), ('saravanua', 'Cakacaka ni Saravanua'), ('yaqona', 'Volitaki Yaqona'), ('dalo', 'Volitaki Dalo'), ('kakana_draudrau', 'Volitaki Kakana Draudrau'), ('sasalu_waitui', 'Volitaki ni Sasalu/Waitui'), ('susu_manumanu', 'Susu Manumanu'), ('konitaraki', 'Cakacaka Konitaraki'), ('liga_buliyaya', 'Cakacaka ni Liga/Buliyaya'), ('lavo_bonisi', 'Vakatubu i Lavo Bonisi'), ('vavalagi', 'Cakacaka mai Vavalagi')], max_length=50)),
                ('selected', models.BooleanField(default=False)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_activities', to='mata_ni_tikina.mntreport')),
            ],
        ),
        migrations.CreateModel(
            name='TikinaSocialIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(choices=[('spiritual_life', 'Spiritual Life'), ('traditional_custom', 'Traditional Custom'), ('drinking_water', 'Drinking Water'), ('food_supply', 'Food Supply'), ('child_welfare_support', 'Child Welfare Support'), ('education', 'Education')], max_length=50)),
                ('trend', models.CharField(blank=True, choices=[('tubucake', 'Tubucake'), ('rawa_vakatikina', 'Rawa Vakatikina'), ('lutusobu', 'Lutu Sobu')], max_length=20)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_indicators', to='mata_ni_tikina.mntreport')),
            ],
        ),
        migrations.CreateModel(
            name='TikinaVillageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('village_name', models.CharField(max_length=150)),
                ('role_performed', models.TextField(blank=True)),
                ('turaga_ni_koro_confirmation', models.CharField(blank=True, max_length=150)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='village_visits', to='mata_ni_tikina.mntreport')),
            ],
        ),
        migrations.CreateModel(
            name='TreePlantingTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_type', models.CharField(choices=[('pine_mahogany', 'Pine/Mahogany'), ('traditional', 'Traditional')], max_length=30)),
                ('training_conducted', models.CharField(blank=True, choices=[('io', 'Io'), ('sega', 'Sega')], max_length=10)),
                ('training_leader', models.CharField(blank=True, max_length=150)),
                ('participants_count', models.PositiveIntegerField(default=0)),
                ('villager_benefit', models.TextField(blank=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_planting_trainings', to='mata_ni_tikina.mntreport')),
            ],
        ),
        migrations.CreateModel(
            name='VagalalaSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_name', models.CharField(max_length=150)),
                ('household_head', models.CharField(blank=True, max_length=150)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagalala_settlements', to='mata_ni_tikina.mntreport')),
            ],
        ),
        migrations.DeleteModel(
            name='DistrictTraining',
        ),
        migrations.DeleteModel(
            name='DistrictVillage',
        ),
        migrations.DeleteModel(
            name='DistrictVisit',
        ),
        migrations.DeleteModel(
            name='InformalSettlement',
        ),
        migrations.DeleteModel(
            name='MataNiTikinaReport',
        ),
        migrations.AddConstraint(
            model_name='mntreport',
            constraint=models.UniqueConstraint(fields=('owner', 'quarter', 'year'), name='one_mnt_report_per_owner_quarter'),
        ),
    ]
