# Generated by Django 5.2 on 2026-07-02 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mata_ni_tikina', '0002_remove_districtvillage_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='koroundertikina',
            name='installed',
            field=models.CharField(blank=True, choices=[('io', 'Io'), ('sega', 'Sega')], max_length=10),
        ),
        migrations.AddField(
            model_name='mntreport',
            name='council_total_attendees',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mntreport',
            name='education_next_quarter_decision',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vagalalasettlement',
            name='family_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vagalalasettlement',
            name='population_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mntreport',
            name='announcements_made_count',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mntreport',
            name='council_head_age',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mntreport',
            name='council_head_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='mntreport',
            name='traditional_announcements_received_count',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='TikinaEducationTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_type', models.CharField(max_length=200)),
                ('training_leader', models.CharField(blank=True, max_length=150)),
                ('participants_count', models.PositiveIntegerField(default=0)),
                ('benefit', models.TextField(blank=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_trainings', to='mata_ni_tikina.mntreport')),
            ],
        ),
    ]
