# Generated by Django 5.2 on 2026-07-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mata_ni_tikina', '0003_koroundertikina_installed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomesourceitem',
            name='category',
            field=models.CharField(choices=[('business', 'Cicivaki Bisinisi'), ('farming', 'Commercial Farm'), ('fishing', 'Commercial Fishing'), ('forest_land_use', 'Forestry and other Land Use'), ('handicrafts', 'Bisinisi ni Handicrafts')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mntreport',
            name='quarter',
            field=models.CharField(choices=[('Q1', 'Q1 - Feperueri kina Epereli'), ('Q2', 'Q2 - Me kina Jiulai'), ('Q3', 'Q3 - Okosita kina Okotopa'), ('Q4', 'Q4 - Noveba kina Janueri')], max_length=2),
        ),
        migrations.AlterField(
            model_name='tikinacoordinationstatus',
            name='entity',
            field=models.CharField(choices=[('yavusa_leadership', 'Liuliu ni Yavusa'), ('mataqali_leadership', 'Liuliu ni Mataqali'), ('church_leadership', 'Liuliu ni Veimata Lotu'), ('organization_leadership', 'Liuliu ni Veimata Soqosoqo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tikinasocialindicator',
            name='indicator',
            field=models.CharField(choices=[('spiritual_life', 'Bula Vakayalo'), ('traditional_custom', 'Tovo Vakavanua'), ('drinking_water', 'Wai ni gunu'), ('food_supply', 'Kakana'), ('child_welfare_support', 'Vukei na Yada kei na Gone luveniyali'), ('education', 'Na Vuli')], max_length=50),
        ),
    ]
