# Generated by Codex on 2026-07-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mata_ni_tikina", "0004_alter_incomesourceitem_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mntreport",
            name="vagalala_family_total",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="mntreport",
            name="vagalala_population_total",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
