# Generated by Django 5.2 on 2026-07-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mata_ni_tikina', '0005_mntreport_vagalala_totals'),
    ]

    operations = [
        migrations.AddField(
            model_name='councilsavingsaccount',
            name='funds_held',
            field=models.CharField(blank=True, choices=[('io', 'Io'), ('sega', 'Sega')], max_length=10),
        ),
    ]
