# Generated by Django 5.2 on 2026-07-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mata_ni_tikina', '0006_councilsavingsaccount_funds_held'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundcollectionchallenge',
            name='challenge',
            field=models.CharField(choices=[('road_access', 'Dredre na gaunisala'), ('no_market', 'Sega na makete ni volivolitaki'), ('no_boat_or_lorry', 'Sega se Dredre na waqa se lori'), ('low_produce_price', 'Sau ca nai voli'), ('low_value_goods', 'Lailai nai yau ni veivoli')], max_length=50),
        ),
    ]
