# Generated by Django 5.2 on 2026-07-07 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mata_ni_tikina', '0008_alter_mntreport_status_mntapprovalaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mntapprovalaction',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_actions', to='mata_ni_tikina.mntreport'),
        ),
        migrations.AlterField(
            model_name='mntapprovalaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mnt_approval_actions', to=settings.AUTH_USER_MODEL),
        ),
    ]
