# Generated by Django 5.2 on 2026-06-17 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TuragaNiYavusaReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(choices=[('Q1', 'Q1 - Jan-Mar'), ('Q2', 'Q2 - Apr-Jun'), ('Q3', 'Q3 - Jul-Sep'), ('Q4', 'Q4 - Oct-Dec')], max_length=2)),
                ('year', models.PositiveIntegerField()),
                ('leader_name', models.CharField(max_length=150)),
                ('tokatoka', models.CharField(max_length=150)),
                ('mataqali', models.CharField(max_length=150)),
                ('yavusa', models.CharField(max_length=150)),
                ('vanua', models.CharField(max_length=150)),
                ('province', models.CharField(max_length=150)),
                ('bosevanua_count', models.PositiveIntegerField(default=0, verbose_name='Number of Bosevanua meetings')),
                ('turaga_ni_mataqali_attended', models.BooleanField(default=False)),
                ('liuliu_ni_tokatoka_attended', models.BooleanField(default=False)),
                ('lewe_ni_yavusa_attended', models.BooleanField(default=False)),
                ('births_registered', models.PositiveIntegerField(default=0, verbose_name='Volai - births entered in Vola ni Kawa Bula')),
                ('deaths_removed', models.PositiveIntegerField(default=0, verbose_name='Bokoci - deaths removed from Vola ni Kawa Bula')),
                ('has_general_yavusa_information', models.CharField(blank=True, choices=[('io', 'Io'), ('sega', 'Sega')], max_length=4)),
                ('bosevanua_topics', models.TextField(blank=True)),
                ('confirmed_turaga_ni_mataqali_titles', models.PositiveIntegerField(default=0)),
                ('chiefly_title_notes', models.TextField(blank=True)),
                ('yaubula_people_culture_language', models.TextField(blank=True, verbose_name='Tamata / Tovo kei na Vosa')),
                ('yaubula_land', models.TextField(blank=True, verbose_name='Qele')),
                ('yaubula_fishing_ground', models.TextField(blank=True, verbose_name='Qoliqoli')),
                ('residents_men', models.PositiveIntegerField(default=0)),
                ('residents_women', models.PositiveIntegerField(default=0)),
                ('residents_children', models.PositiveIntegerField(default=0)),
                ('away_men', models.PositiveIntegerField(default=0, verbose_name='Men living away for work')),
                ('away_women', models.PositiveIntegerField(default=0, verbose_name='Women living away for work')),
                ('away_children', models.PositiveIntegerField(default=0, verbose_name='Children living away')),
                ('corrections_visit_plan', models.CharField(blank=True, choices=[('io', 'Io'), ('sega', 'Sega')], max_length=4)),
                ('attends_village_meeting', models.CharField(blank=True, choices=[('io', 'Io'), ('sega', 'Sega')], max_length=4)),
                ('attends_district_meeting', models.CharField(blank=True, choices=[('io', 'Io'), ('sega', 'Sega')], max_length=4)),
                ('denomination_count', models.PositiveIntegerField(default=0)),
                ('church_presents_plan_to_vanua', models.CharField(blank=True, choices=[('io', 'Io'), ('sega', 'Sega')], max_length=4)),
                ('church_meets_vanua_needs', models.CharField(blank=True, choices=[('io', 'Io'), ('sega', 'Sega')], max_length=4)),
                ('yavusa_challenges', models.TextField(blank=True)),
                ('mataqali_challenges', models.TextField(blank=True)),
                ('tokatoka_challenges', models.TextField(blank=True)),
                ('roko_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='yavusa_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'quarter', 'year'), name='one_yavusa_report_per_quarter')],
            },
        ),
    ]
