# Generated by Django 5.2 on 2026-06-30 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turaga_ni_yavusa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TNYReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(choices=[('Q1', 'Q1 - January to March'), ('Q2', 'Q2 - April to June'), ('Q3', 'Q3 - July to September'), ('Q4', 'Q4 - October to December')], max_length=2)),
                ('year', models.PositiveIntegerField()),
                ('full_name', models.CharField(max_length=150)),
                ('tokatoka', models.CharField(max_length=150)),
                ('mataqali', models.CharField(max_length=150)),
                ('yavusa', models.CharField(max_length=150)),
                ('vanua', models.CharField(max_length=150)),
                ('koro', models.CharField(blank=True, max_length=150)),
                ('bosevanua_meeting_frequency', models.CharField(choices=[('1', 'Dua'), ('2', 'Rua'), ('3', 'Tolu+')], max_length=1)),
                ('bosevanua_turaga_ni_mataqali_count', models.PositiveIntegerField(default=0)),
                ('bosevanua_liuliu_ni_tokatoka_count', models.PositiveIntegerField(default=0)),
                ('bosevanua_lewe_ni_yavusa_count', models.PositiveIntegerField(default=0)),
                ('genealogy_recorded_count', models.PositiveIntegerField(default=0)),
                ('genealogy_removed_count', models.PositiveIntegerField(default=0)),
                ('yavusa_report_filed', models.CharField(blank=True, choices=[('io', 'Io'), ('sega', 'Sega')], max_length=10)),
                ('yavusa_report_topics', models.TextField(blank=True)),
                ('yavusa_report_notes', models.TextField(blank=True)),
                ('confirmed_titles_this_period', models.PositiveIntegerField(default=0)),
                ('titles_additional_notes', models.TextField(blank=True)),
                ('language_custom_initiatives', models.TextField(blank=True)),
                ('land_initiatives', models.TextField(blank=True)),
                ('fishing_ground_initiatives', models.TextField(blank=True)),
                ('resident_turaga_count', models.PositiveIntegerField(default=0)),
                ('resident_marama_count', models.PositiveIntegerField(default=0)),
                ('resident_gone_count', models.PositiveIntegerField(default=0)),
                ('away_turaga_count', models.PositiveIntegerField(default=0)),
                ('away_marama_count', models.PositiveIntegerField(default=0)),
                ('away_gone_count', models.PositiveIntegerField(default=0)),
                ('has_member_visitation_plan', models.CharField(blank=True, choices=[('io', 'Io'), ('sega', 'Sega')], max_length=10)),
                ('attends_bose_vakoro', models.CharField(blank=True, choices=[('io', 'Io'), ('sega', 'Sega')], max_length=10)),
                ('attends_bose_ni_tikina', models.CharField(blank=True, choices=[('io', 'Io'), ('sega', 'Sega')], max_length=10)),
                ('churches_in_yavusa_count', models.PositiveIntegerField(default=0)),
                ('church_follows_vanua_program', models.CharField(blank=True, choices=[('io', 'Io'), ('sega', 'Sega')], max_length=10)),
                ('church_meets_vanua_needs', models.CharField(blank=True, choices=[('io', 'Io'), ('sega', 'Sega')], max_length=10)),
                ('yavusa_obligations', models.TextField(blank=True)),
                ('mataqali_obligations', models.TextField(blank=True)),
                ('tokatoka_obligations', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tny_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('turaga_ni_yavusa', 'Turaga ni Yavusa'), ('turaga_ni_koro', 'Turaga ni Koro'), ('roko_veiqaravi', 'Roko Veiqaravi'), ('roko_tui', 'Roko Tui')], max_length=50)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('signed', models.BooleanField(default=False)),
                ('signed_date', models.DateField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='turaga_ni_yavusa.tnyreport')),
            ],
        ),
        migrations.DeleteModel(
            name='TuragaNiYavusaReport',
        ),
        migrations.AddConstraint(
            model_name='tnyreport',
            constraint=models.UniqueConstraint(fields=('owner', 'quarter', 'year'), name='one_tny_report_per_owner_quarter'),
        ),
    ]
