# Generated by Codex on 2026-07-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("turaga_ni_yavusa", "0003_alter_tnyreport_quarter"),
    ]

    operations = [
        migrations.AddField(
            model_name="tnyreport",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="tnyreport",
            name="phone_number",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="tnyreport",
            name="tikina",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
