# Generated by Django 5.2 on 2026-07-06 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turaga_ni_yavusa', '0004_tnyreport_contact_tikina'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnyreport',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted to Roko Tui'), ('approved_roko', 'Approved by Roko Tui'), ('returned_roko', 'Returned by Roko Tui'), ('rejected_roko', 'Rejected by Roko Tui')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='TNYApprovalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_full_name', models.CharField(max_length=150)),
                ('user_role', models.CharField(max_length=100)),
                ('action_type', models.CharField(choices=[('submit', 'Submit'), ('approve', 'Approve'), ('return', 'Return'), ('reject', 'Reject'), ('comment', 'Comment')], max_length=30)),
                ('from_status', models.CharField(blank=True, max_length=40)),
                ('to_status', models.CharField(blank=True, max_length=40)),
                ('comment', models.TextField(blank=True)),
                ('digital_acknowledgement', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_actions', to='turaga_ni_yavusa.tnyreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tny_approval_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Turaga ni Yavusa Approval Action',
                'verbose_name_plural': 'Turaga ni Yavusa Approval Actions',
                'ordering': ['created_at', 'pk'],
            },
        ),
    ]
