# Generated by Django 5.2 on 2026-07-07 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turaga_ni_yavusa', '0005_alter_tnyreport_status_tnyapprovalaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnyapprovalaction',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_actions', to='turaga_ni_yavusa.tnyreport'),
        ),
        migrations.AlterField(
            model_name='tnyapprovalaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tny_approval_actions', to=settings.AUTH_USER_MODEL),
        ),
    ]
