# Generated by Django 5.2 on 2026-06-24 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TikinaReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tikina', models.CharField(choices=[('Lakeba', 'Lakeba'), ('Oneata', 'Oneata'), ('Moce', 'Moce'), ('Kabara', 'Kabara'), ('Fulaga', 'Fulaga'), ('Ogea', 'Ogea'), ('Vatoa', 'Vatoa'), ('Ono-i-Lau', 'Ono-i-Lau'), ('Cicia', 'Cicia'), ('Nayau', 'Nayau'), ('Vanuabalavu', 'Vanuabalavu'), ('Mago', 'Mago')], max_length=100)),
                ('summary', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
