# Generated by Django 5.2 on 2026-06-25 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_create_role_groups'),
        ('tikina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tikinareport',
            name='tikina',
            field=models.CharField(choices=[('lakeba', 'Lakeba'), ('nayau', 'Nayau'), ('oneata', 'Oneata'), ('moce', 'Moce'), ('kabara', 'Kabara'), ('fulaga', 'Fulaga'), ('ono_i_lau', 'Ono-i-Lau'), ('lomaloma', 'Lomaloma'), ('mualevu', 'Mualevu'), ('cicia', 'Cicia'), ('moala', 'Moala'), ('matuku', 'Matuku'), ('totoya', 'Totoya')], max_length=100),
        ),
        migrations.CreateModel(
            name='Tikina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(help_text='Official order number (1-13)', unique=True)),
                ('name', models.CharField(help_text='Official Fijian name in UPPERCASE', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('koro_turaga', models.CharField(help_text='Principal village / seat of the Tikina', max_length=100)),
                ('official_koro_count', models.PositiveSmallIntegerField(default=0)),
                ('island_group', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='tikina/covers/')),
                ('mata_ni_tikina', models.OneToOneField(blank=True, help_text='The Mata ni Tikina user assigned to this Tikina', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tikina_managed', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Tikina',
                'verbose_name_plural': 'Tikina',
                'ordering': ['number'],
            },
        ),
    ]
