# Generated by Codex on 2026-06-26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def migrate_tikina_fk(apps, schema_editor):
    TikinaReport = apps.get_model("tikina", "TikinaReport")
    Tikina = apps.get_model("tikina", "Tikina")

    for report in TikinaReport.objects.exclude(tikina_old=""):
        raw_value = (report.tikina_old or "").strip()
        slug_guess = raw_value.lower().replace("_", "-").replace(" ", "-")
        match = Tikina.objects.filter(slug__iexact=slug_guess).first()
        if not match:
            match = Tikina.objects.filter(name__iexact=raw_value).first()
        if match:
            report.tikina_id = match.pk
            report.save(update_fields=["tikina_id"])


def reverse_tikina_fk(apps, schema_editor):
    TikinaReport = apps.get_model("tikina", "TikinaReport")

    for report in TikinaReport.objects.select_related("tikina").filter(tikina__isnull=False):
        report.tikina_old = report.tikina.slug
        report.save(update_fields=["tikina_old"])


class Migration(migrations.Migration):

    dependencies = [
        ("tikina", "0002_alter_tikinareport_tikina_tikina"),
    ]

    operations = [
        migrations.AddField(
            model_name="tikina",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="tikina",
            name="mataqali_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tikina",
            name="population",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="TikinaGalleryImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="tikina/gallery/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "tikina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="tikina.tikina",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="tikinareport",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("general", "General Report"),
                    ("population", "Population Update"),
                    ("infrastructure", "Infrastructure Report"),
                ],
                default="general",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="tikinareport",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RenameField(
            model_name="tikinareport",
            old_name="tikina",
            new_name="tikina_old",
        ),
        migrations.AddField(
            model_name="tikinareport",
            name="tikina",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reports",
                to="tikina.tikina",
            ),
        ),
        migrations.RunPython(migrate_tikina_fk, reverse_tikina_fk),
        migrations.RemoveField(
            model_name="tikinareport",
            name="tikina_old",
        ),
    ]
