# Generated by Django 5.2 on 2026-06-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Koro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('is_koro_turaga', models.BooleanField(default=False, help_text='True if this village is the Koro Turaga (principal village) of its Tikina')),
                ('population', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='koro/covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Koro',
                'verbose_name_plural': 'Koro',
                'ordering': ['tikina__number', '-is_koro_turaga', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='kororeport',
            name='tikina',
            field=models.CharField(choices=[('lakeba', 'Lakeba'), ('nayau', 'Nayau'), ('oneata', 'Oneata'), ('moce', 'Moce'), ('kabara', 'Kabara'), ('fulaga', 'Fulaga'), ('ono_i_lau', 'Ono-i-Lau'), ('lomaloma', 'Lomaloma'), ('mualevu', 'Mualevu'), ('cicia', 'Cicia'), ('moala', 'Moala'), ('matuku', 'Matuku'), ('totoya', 'Totoya')], max_length=100),
        ),
    ]
