# Generated by Django 5.2 on 2026-06-25 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_create_role_groups'),
        ('koro', '0002_koro_alter_kororeport_tikina'),
        ('tikina', '0002_alter_tikinareport_tikina_tikina'),
    ]

    operations = [
        migrations.AddField(
            model_name='koro',
            name='tikina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='koro', to='tikina.tikina'),
        ),
        migrations.AddField(
            model_name='koro',
            name='turaga_ni_koro',
            field=models.OneToOneField(blank=True, help_text='The Turaga ni Koro user assigned to this village', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='koro_managed', to='accounts.userprofile'),
        ),
        migrations.AddConstraint(
            model_name='koro',
            constraint=models.UniqueConstraint(fields=('name', 'tikina'), name='unique_koro_name_per_tikina'),
        ),
        migrations.AddConstraint(
            model_name='koro',
            constraint=models.UniqueConstraint(condition=models.Q(('is_koro_turaga', True)), fields=('tikina',), name='unique_koro_turaga_per_tikina'),
        ),
    ]
