# Generated by Codex on 2026-06-26

import django.db.models.deletion
from django.db import migrations, models


def migrate_koro_report_tikina_fk(apps, schema_editor):
    KoroReport = apps.get_model("koro", "KoroReport")
    Tikina = apps.get_model("tikina", "Tikina")

    for report in KoroReport.objects.exclude(tikina_old=""):
        raw_value = (report.tikina_old or "").strip()
        slug_guess = raw_value.lower().replace("_", "-").replace(" ", "-")
        match = Tikina.objects.filter(slug__iexact=slug_guess).first()
        if not match:
            match = Tikina.objects.filter(name__iexact=raw_value).first()
        if match:
            report.tikina_id = match.pk
            report.save(update_fields=["tikina_id"])


def reverse_koro_report_tikina_fk(apps, schema_editor):
    KoroReport = apps.get_model("koro", "KoroReport")

    for report in KoroReport.objects.select_related("tikina").filter(tikina__isnull=False):
        report.tikina_old = report.tikina.slug
        report.save(update_fields=["tikina_old"])


class Migration(migrations.Migration):

    dependencies = [
        ("tikina", "0003_tikina_gallery_report_fk_and_stats"),
        ("koro", "0003_koro_tikina_koro_turaga_ni_koro_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="kororeport",
            old_name="tikina",
            new_name="tikina_old",
        ),
        migrations.AddField(
            model_name="kororeport",
            name="tikina",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="koro_reports",
                to="tikina.tikina",
            ),
        ),
        migrations.RunPython(migrate_koro_report_tikina_fk, reverse_koro_report_tikina_fk),
        migrations.RemoveField(
            model_name="kororeport",
            name="tikina_old",
        ),
    ]
