# Generated by Django 5.2 on 2026-07-14 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koro', '0004_kororeport_tikina_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='KoroDroneVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='drone_videos/%Y/%m/')),
                ('video_url', models.URLField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='drone_videos/thumbnails/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('koro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drone_videos', to='koro.koro')),
            ],
            options={
                'ordering': ['order', '-uploaded_at'],
            },
        ),
    ]
