# Generated by Django 5.2 on 2026-06-17 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TNKReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('village', models.CharField(max_length=150)),
                ('district', models.CharField(max_length=150)),
                ('province', models.CharField(max_length=150)),
                ('village_headman_name', models.CharField(max_length=150)),
                ('village_headman_age', models.PositiveIntegerField(blank=True, null=True)),
                ('appointment_month_year', models.CharField(blank=True, max_length=100)),
                ('village_meetings_count', models.PositiveIntegerField(default=0)),
                ('household_count', models.PositiveIntegerField(default=0)),
                ('correction_reintegration_plan', models.TextField(blank=True)),
                ('water_problem_responsible_agency', models.TextField(blank=True)),
                ('water_challenges', models.TextField(blank=True)),
                ('toilet_wastewater_agency', models.TextField(blank=True)),
                ('ivdp_progress_started', models.CharField(blank=True, choices=[('io', 'Io'), ('sega', 'Sega')], max_length=10)),
                ('ivdp_unfinished_reason', models.TextField(blank=True)),
                ('yaubula_current_plan', models.TextField(blank=True)),
                ('yaubula_management_plan', models.TextField(blank=True)),
                ('disaster_current_plan', models.TextField(blank=True)),
                ('disaster_future_plan', models.TextField(blank=True)),
                ('has_evacuation_centre', models.CharField(blank=True, choices=[('io', 'Io'), ('sega', 'Sega')], max_length=10)),
                ('evacuation_centre_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('has_male_female_restrooms', models.CharField(blank=True, choices=[('io', 'Io'), ('sega', 'Sega')], max_length=10)),
                ('climate_change_impact', models.CharField(blank=True, choices=[('io', 'Io'), ('sega', 'Sega')], max_length=10)),
                ('climate_change_impact_details', models.TextField(blank=True)),
                ('climate_change_solution_done', models.CharField(blank=True, choices=[('io', 'Io'), ('sega', 'Sega')], max_length=10)),
                ('climate_change_solution_details', models.TextField(blank=True)),
                ('bose_vanua_count', models.PositiveIntegerField(default=0)),
                ('roko_veivuke_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TNK Report',
                'verbose_name_plural': 'TNK Reports',
                'ordering': ['-year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('liuliu_bose_vakoro', 'Liuliu ni Bose Vakoro'), ('turaga_ni_koro', 'Turaga ni Koro'), ('nasi_ni_koro', 'Nasi ni Koro'), ('roko_veivuke', 'Roko Veivuke'), ('roko_tui', 'Roko Tui')], max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('signed', models.BooleanField(default=False)),
                ('signed_date', models.DateField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='turani.tnkreport')),
            ],
        ),
        migrations.CreateModel(
            name='PopulationAgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('yalewa', 'Yalewa'), ('tagane', 'Tagane')], max_length=20)),
                ('age_group', models.CharField(choices=[('0_10', '0-10'), ('11_20', '11-20'), ('21_30', '21-30'), ('31_40', '31-40'), ('41_50', '41-50'), ('51_60', '51-60'), ('61_plus', '61+')], max_length=20)),
                ('count', models.PositiveIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='population', to='turani.tnkreport')),
            ],
        ),
        migrations.CreateModel(
            name='LawOffence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offence_name', models.CharField(max_length=255)),
                ('count', models.PositiveIntegerField(default=0)),
                ('reported_to_law', models.CharField(blank=True, choices=[('io', 'Io'), ('sega', 'Sega')], max_length=10)),
                ('reason_not_reported', models.TextField(blank=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='law_offences', to='turani.tnkreport')),
            ],
        ),
        migrations.CreateModel(
            name='IVDPProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('project_number', models.PositiveIntegerField(blank=True, null=True)),
                ('priority_area', models.PositiveSmallIntegerField(choices=[(1, 'Veiliutaki Vinaka'), (2, 'Tiko Vinaka'), (3, 'Rawa Ka Vakaiyau'), (4, 'Maroroi Ni Yau Bula'), (5, 'Veiliutaki Vinaka Ni Vanua')])),
                ('work_done', models.TextField(blank=True)),
                ('application_prepared', models.CharField(blank=True, choices=[('io', 'Io'), ('sega', 'Sega')], max_length=10)),
                ('funding_agency', models.CharField(blank=True, max_length=200)),
                ('materials_received', models.CharField(blank=True, choices=[('io', 'Io'), ('sega', 'Sega')], max_length=10)),
                ('problem_reason', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ivdp_projects', to='turani.tnkreport')),
            ],
        ),
        migrations.CreateModel(
            name='IVDPImplementationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=200)),
                ('responsibility', models.CharField(blank=True, max_length=200)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('consultation_approval', models.BooleanField(default=False)),
                ('commencement', models.BooleanField(default=False)),
                ('priority_area_achieved_50', models.BooleanField(default=False)),
                ('project_completion', models.BooleanField(default=False)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ivdp_schedule', to='turani.tnkreport')),
            ],
        ),
        migrations.CreateModel(
            name='HousingCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_type', models.CharField(choices=[('house', 'Vale'), ('kitchen', 'Vale ni Kuro'), ('bathroom', 'Vale ni Sili'), ('toilet', 'Vale Lailai')], max_length=30)),
                ('material', models.CharField(choices=[('simede', 'Simede'), ('kau', 'Kau'), ('kava', 'Kava'), ('vakaviti', 'Vakaviti')], max_length=30)),
                ('count', models.PositiveIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housing_counts', to='turani.tnkreport')),
            ],
        ),
        migrations.CreateModel(
            name='HealthConditionCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_name', models.CharField(max_length=200)),
                ('age_group', models.CharField(choices=[('0_14', 'Gone lalai 0-14'), ('15_35', 'Tabagone 15-35'), ('36_60', 'Uabula 36-60'), ('60_plus', 'Qase 60+')], max_length=20)),
                ('count', models.PositiveIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_conditions', to='turani.tnkreport')),
            ],
        ),
        migrations.CreateModel(
            name='EvacuationCentreMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('simede', 'Simede'), ('kau', 'Kau'), ('kava', 'Kava'), ('vakaviti', 'Vakaviti')], max_length=30)),
                ('selected', models.BooleanField(default=False)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evacuation_centre_materials', to='turani.tnkreport')),
            ],
        ),
        migrations.CreateModel(
            name='ElectricitySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('fea', 'FEA'), ('village_generator', 'Idini ni Koro'), ('windmill', 'Windmill'), ('private_generator', 'Idini Vakaitaukei'), ('kerosene', 'Karasini/Tabucagi'), ('benzene', 'Benisini'), ('solar', 'Solar Energy'), ('hydro', 'Hydro')], max_length=50)),
                ('house_count', models.PositiveIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electricity_sources', to='turani.tnkreport')),
            ],
        ),
        migrations.CreateModel(
            name='DisabilityCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disability_name', models.CharField(max_length=200)),
                ('age_group', models.CharField(choices=[('0_14', 'Gone lalai 0-14'), ('15_35', 'Tabagone 15-35'), ('36_60', 'Uabula 36-60'), ('60_plus', 'Qase 60+')], max_length=20)),
                ('count', models.PositiveIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disabilities', to='turani.tnkreport')),
            ],
        ),
        migrations.CreateModel(
            name='CulturalKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge_type', models.CharField(max_length=200)),
                ('preservation_plan', models.TextField(blank=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultural_knowledge', to='turani.tnkreport')),
            ],
        ),
        migrations.CreateModel(
            name='CropCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('kakana_draudrau', 'Kakana Draudrau'), ('kakana_dina', 'Kakana Dina')], max_length=30)),
                ('crop_name', models.CharField(max_length=100)),
                ('plantation_count', models.PositiveIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='turani.tnkreport')),
            ],
        ),
        migrations.CreateModel(
            name='CorrectionReturnee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('rehabilitation_done', models.TextField(blank=True)),
                ('current_activity', models.TextField(blank=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_returnees', to='turani.tnkreport')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('owner_name', models.CharField(max_length=150)),
                ('licensed', models.CharField(blank=True, choices=[('io', 'Io'), ('sega', 'Sega')], max_length=10)),
                ('business_type', models.CharField(blank=True, max_length=200)),
                ('years_running', models.CharField(blank=True, max_length=100)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='turani.tnkreport')),
            ],
        ),
        migrations.CreateModel(
            name='ToiletType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toilet_type', models.CharField(choices=[('sovawai', 'Sovawai'), ('keli', 'Keli'), ('sewer_line', 'Dre - Sewer Line'), ('septic_simede', 'Dre - Septic Tank Simede'), ('septic_dramu', 'Dre - Septic Tank Dramu'), ('compost', 'Compost'), ('none', 'Sega na Valelailai')], max_length=40)),
                ('count', models.PositiveIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toilet_types', to='turani.tnkreport')),
            ],
        ),
        migrations.CreateModel(
            name='TraditionalTitleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_type', models.CharField(choices=[('turaga_ni_yavusa', 'Turaga ni Yavusa'), ('turaga_ni_mataqali', 'Turaga ni Mataqali')], max_length=50)),
                ('yavusa_mataqali_count', models.PositiveIntegerField(default=0)),
                ('confirmed_count', models.PositiveIntegerField(default=0)),
                ('unconfirmed_count', models.PositiveIntegerField(default=0)),
                ('being_processed', models.CharField(blank=True, choices=[('io', 'Io'), ('sega', 'Sega')], max_length=10)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traditional_titles', to='turani.tnkreport')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_type', models.CharField(choices=[('general', 'Vuli/Veivakararamataki'), ('business', 'Vuli ni Bisinisi'), ('vanua', 'Vuli ni Matabose ni Veika Vakaitaukei')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True)),
                ('participants_count', models.PositiveIntegerField(default=0)),
                ('outcome', models.TextField(blank=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='turani.tnkreport')),
            ],
        ),
        migrations.CreateModel(
            name='VillageAssetSaving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.CharField(choices=[('io', 'Io'), ('sega', 'Sega')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets_savings', to='turani.tnkreport')),
            ],
        ),
        migrations.CreateModel(
            name='VillageCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee_type', models.CharField(choices=[('development', 'Veivakatorocaketaki'), ('health', 'Tiko Bulabula'), ('water', 'Wai'), ('yaubula_disaster', 'Yau Bula/Leqa Tubu Koso'), ('education', 'Vuli'), ('youth', 'Tabagone'), ('women', 'Marama'), ('law', 'Lawa')], max_length=50)),
                ('exists', models.CharField(choices=[('io', 'Io'), ('sega', 'Sega')], max_length=10)),
                ('male_members', models.PositiveIntegerField(default=0)),
                ('female_members', models.PositiveIntegerField(default=0)),
                ('meetings_last_3_months', models.PositiveIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committees', to='turani.tnkreport')),
            ],
        ),
        migrations.CreateModel(
            name='VillageMeetingDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.TextField()),
                ('implemented', models.CharField(choices=[('io', 'Io'), ('sega', 'Sega')], max_length=10)),
                ('reason_not_implemented', models.TextField(blank=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_decisions', to='turani.tnkreport')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_type', models.CharField(choices=[('yasana', 'Valevolavola ni Yasana'), ('government', 'Matanitu/Taudaku ni Matanitu')], max_length=20)),
                ('officer_name', models.CharField(max_length=150)),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='turani.tnkreport')),
            ],
        ),
        migrations.CreateModel(
            name='WasteManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village_dump', models.CharField(blank=True, choices=[('io', 'Io'), ('sega', 'Sega')], max_length=10)),
                ('village_boundary_clean', models.CharField(blank=True, choices=[('io', 'Io'), ('sega', 'Sega')], max_length=10)),
                ('household_dump', models.CharField(blank=True, choices=[('io', 'Io'), ('sega', 'Sega')], max_length=10)),
                ('garbage_truck', models.CharField(blank=True, choices=[('io', 'Io'), ('sega', 'Sega')], max_length=10)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='waste_management', to='turani.tnkreport')),
            ],
        ),
        migrations.CreateModel(
            name='WaterCommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_committee_members', to='turani.tnkreport')),
            ],
        ),
        migrations.CreateModel(
            name='WaterCommitteeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.BooleanField(default=False)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_committee_answers', to='turani.tnkreport')),
            ],
        ),
        migrations.CreateModel(
            name='WaterSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('uciwai', 'Uciwai'), ('waivure', 'Waivure'), ('wai_ni_uca', 'Wai ni Uca'), ('toevu', 'Toevu'), ('taqe_ni_wai', 'Taqe ni Wai'), ('waf', 'WAF')], max_length=30)),
                ('selected', models.BooleanField(default=False)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_sources', to='turani.tnkreport')),
            ],
        ),
    ]
