# Generated by Django 5.2 on 2026-06-17 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turani', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tnkreport',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tnk_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tnkreport',
            name='quarter',
            field=models.CharField(choices=[('Q1', 'Q1 - January to March'), ('Q2', 'Q2 - April to June'), ('Q3', 'Q3 - July to September'), ('Q4', 'Q4 - October to December')], max_length=2),
        ),
        migrations.AddConstraint(
            model_name='tnkreport',
            constraint=models.UniqueConstraint(fields=('owner', 'quarter', 'year'), name='one_tnk_report_per_owner_quarter'),
        ),
    ]
