# Generated by Django 5.2 on 2026-06-26 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turani', '0002_tnkreport_owner_alter_tnkreport_quarter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tnkreport',
            name='toilet_wastewater_challenges',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tnkreport',
            name='water_sanitation_challenges',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_type',
            field=models.CharField(choices=[('yasana', 'Valevolavola ni Yasana'), ('government', 'Matanitu  se Taudaku ni Matanitu')], max_length=20),
        ),
        migrations.CreateModel(
            name='BusinessTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True)),
                ('participants_count', models.PositiveIntegerField(default=0)),
                ('outcome', models.TextField(blank=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_trainings', to='turani.tnkreport')),
            ],
        ),
    ]
