# Generated by Django 5.2 on 2026-07-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turani', '0004_tnkreport_status_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnkreport',
            name='quarter',
            field=models.CharField(choices=[('Q1', 'Q1 - Feperueri kina Epereli'), ('Q2', 'Q2 - Me kina Jiulai'), ('Q3', 'Q3 - Okosita kina Okotopa'), ('Q4', 'Q4 - Noveba kina Janueri')], max_length=2),
        ),
    ]
