# Generated by Codex on 2026-07-06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_submitted_status(apps, schema_editor):
    TNKReport = apps.get_model("turani", "TNKReport")
    TNKReport.objects.filter(status="submitted").update(status="submitted_mata")


def reverse_submitted_status(apps, schema_editor):
    TNKReport = apps.get_model("turani", "TNKReport")
    TNKReport.objects.filter(status="submitted_mata").update(status="submitted")


class Migration(migrations.Migration):

    dependencies = [
        ("turani", "0005_alter_tnkreport_quarter"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="tnkreport",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted_mata", "Submitted to Mata ni Tikina"),
                    ("returned_turaga", "Returned to Turaga ni Koro"),
                    ("approved_mata", "Approved by Mata ni Tikina"),
                    ("submitted_liuliu", "Submitted to Liuliu ni Yavusa"),
                    ("approved_liuliu", "Approved by Liuliu ni Yavusa"),
                    ("submitted_assistant", "Submitted to Assistant Roko"),
                    ("recommended_assistant", "Recommended by Assistant Roko"),
                    ("submitted_roko", "Submitted to Roko Tui"),
                    ("final_approved", "Final Approved"),
                    ("rejected", "Rejected"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=40,
            ),
        ),
        migrations.RunPython(migrate_submitted_status, reverse_submitted_status),
        migrations.CreateModel(
            name="TNKApprovalAction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_full_name", models.CharField(max_length=150)),
                ("user_role", models.CharField(max_length=100)),
                ("action_type", models.CharField(choices=[("submit", "Submit"), ("approve", "Approve"), ("return", "Return"), ("reject", "Reject"), ("recommend", "Recommend"), ("final_approve", "Final approve"), ("archive", "Archive"), ("comment", "Comment")], max_length=30)),
                ("from_status", models.CharField(blank=True, max_length=40)),
                ("to_status", models.CharField(blank=True, max_length=40)),
                ("comment", models.TextField(blank=True)),
                ("digital_acknowledgement", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("report", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="approval_actions", to="turani.tnkreport")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="tnk_approval_actions", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "TNK Approval Action",
                "verbose_name_plural": "TNK Approval Actions",
                "ordering": ["created_at", "pk"],
            },
        ),
    ]
